'use client'

import { motion } from 'framer-motion'
import { FileText, ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import MarketingNav from '@/components/marketing/MarketingNav'
import MarketingFooter from '@/components/marketing/MarketingFooter'

export default function TermsPage() {
  const lastUpdated = 'April 03, 2026'

  return (
    <div className="min-h-screen bg-charcoal-DEFAULT">
      <MarketingNav />

      <div className="pt-32 pb-24 px-6">
        <div className="max-w-3xl mx-auto">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-12"
          >
            <Link href="/" className="text-stratiq-blue hover:text-stratiq-blue-light flex items-center gap-2 text-[13px] font-bold mb-8 transition-colors">
              <ArrowLeft size={14} /> Back to Home
            </Link>
            <div className="flex items-center gap-4 mb-6">
               <div className="w-10 h-10 rounded-xl bg-stratiq-blue/10 flex items-center justify-center">
                  <FileText size={20} className="text-stratiq-blue" />
               </div>
               <h1 className="text-[32px] md:text-[42px] font-display font-bold text-ink-DEFAULT">
                 Terms of Service
               </h1>
            </div>
            <p className="text-[14px] text-ink-faint font-mono tracking-wider">
               LAST UPDATED: {lastUpdated}
            </p>
          </motion.div>

          {/* Content */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.1 }}
            className="prose prose-invert prose-brand max-w-none prose-h2:font-display prose-h2:text-[24px] prose-h2:mt-12 prose-h2:mb-6 prose-p:text-ink-muted prose-p:text-[15px] prose-p:leading-relaxed"
          >
            <p>
              By accessing or using the STRATIQ platform, you agree to comply with and be bound by the following terms and conditions of service.
            </p>

            <h2>1. Service Description</h2>
            <p>
              STRATIQ provides a Decision Intelligence platform that allows users to model, simulate, and analyze decisions using structured data frameworks. The service is provided &quot;as is&quot; and intended for analytical support, not as legal or financial advice.
            </p>

            <h2>2. User Responsibilities</h2>
            <p>
              As a user of STRATIQ, you are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree not to:
            </p>
            <ul className="text-ink-muted text-[15px] space-y-2 list-disc pl-6">
              <li>Use the service for any illegal or unauthorized purpose.</li>
              <li>Attempt to reverse engineer the simulation engine or any proprietary algorithms.</li>
              <li>Upload any content that violates third-party intellectual property rights.</li>
            </ul>

            <h2>3. Intellectual Property</h2>
            <p>
               All decision models, reports, and data generated by you using the STRATIQ platform are your exclusive property. STRATIQ retains ownership of the platform itself, including all software, design elements, and algorithms used to process your data.
            </p>

            <h2>4. Subscription & Payments</h2>
            <p>
              Access to some features of STRATIQ may require a paid subscription. Billing is managed through our payment processor and is subject to their terms of service. You can cancel your subscription at any time; however, no partial refunds are provided for current biling cycles.
            </p>

            <h2>5. Disclaimer of Accountability</h2>
            <p>
              STRATIQ is an intelligence tool designed to support decision-making. The platform does not make decisions for you. Any action taken based on the outputs of STRATIQ is the sole responsibility of the user. STRATIQ is not liable for outcomes resulting from decisions made using our platform.
            </p>

            <h2>6. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of these terms or if your account poses a security risk to our platform.
            </p>

            <h2>7. Governing Law</h2>
            <p>
              These terms are governed by and construed in accordance with the laws of the jurisdiction in which STRATIQ is registered, without regard to its conflict of law principles.
            </p>
          </motion.div>
        </div>
      </div>

      <MarketingFooter />
    </div>
  )
}
